name: 'Foundry Release Action'
description: 'GitHub Action to Release Foundry VTT Systems and Modules'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'