name: 'Foundry Release Action'
description: 'GitHub Action to Release Foundry VTT Systems and Modules'
inputs:
  actionToken:
    description: 'Github Token'
    required: true
    default: 'World'
  manifestFileName:
    description: 'Name of the Foundry Manifest File, either system.json or module.json'
    required: true
    default: 'module.json'
  manifestProtectedTrue:
    description: 'Set to true to set protected: true in the manifest during the release'
    required: false
    default: 'false'
runs:
  using: 'node12'
  main: 'index.js'